[package]
name = "maleo"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "25"
glyphon = "0.9"
bytemuck = { version = "1.14", features = ["derive"] }
winit = "0.30"
pollster = "0.3"

[dev-dependencies]
winit = "0.30"
pollster = "0.3"
