[package]
name = "rentex"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = "0.19"
glyphon = "0.5"
bytemuck = { version = "1.14", features = ["derive"] }
winit = "0.29"
pollster = "0.3"

[dev-dependencies]
winit = "0.29"
pollster = "0.3"
